"""Changed GTIN to String (e.g. 0020714052959)

Revision ID: 2d4ca80ea70a
Revises: fa4ea47f90c2
Create Date: 2025-04-09 22:53:13.279052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4ca80ea70a'
down_revision: Union[str, None] = 'fa4ea47f90c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'GTIN',
               existing_type=sa.NUMERIC(precision=14, scale=0),
               type_=sa.String(length=14),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'GTIN',
               existing_type=sa.String(length=14),
               type_=sa.NUMERIC(precision=14, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###
