"""Initial commit

Revision ID: 55c07cab1a36
Revises: 
Create Date: 2025-04-04 21:00:23.747184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c07cab1a36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=2), nullable=False),
    sa.Column('GTIN', sa.Integer(), nullable=False),
    sa.Column('SKU', sa.String(), nullable=True),
    sa.Column('pack_size', sa.Integer(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_GTIN'), 'products', ['GTIN'], unique=False)
    op.create_index(op.f('ix_products_SKU'), 'products', ['SKU'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_SKU'), table_name='products')
    op.drop_index(op.f('ix_products_GTIN'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
