"""Accustomed database for nullable entries

Revision ID: 9a5f431af57f
Revises: 55c07cab1a36
Create Date: 2025-04-09 20:02:09.634284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5f431af57f'
down_revision: Union[str, None] = '55c07cab1a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('portfolio', sa.String(), nullable=True))
    op.add_column('products', sa.Column('volume', sa.Numeric(), nullable=True))
    op.add_column('products', sa.Column('resource_identifier', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'resource_identifier')
    op.drop_column('products', 'volume')
    op.drop_column('products', 'portfolio')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
