"""Changed price to be at most 1 million, with 2 floating precisions

Revision ID: fa4ea47f90c2
Revises: 4b5e3e5e5e03
Create Date: 2025-04-09 22:51:38.367710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4ea47f90c2'
down_revision: Union[str, None] = '4b5e3e5e5e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###
